#
# Copyright 2016 Jeff Bush
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

all:
	cd hello_world && make
	cd cup && make
	cd luigi_circuit && make
	cd mandelbrot && make
	cd pinocchio && make
	cd plasma && make
	cd pyramide && make
	cd rotozoom && make
	cd rotozoom_without_UART && make
	cd scene_viewer && make
	cd shadow_map && make

clean:
	cd hello_world && make clean
	cd cup && make clean
	cd luigi_circuit && make clean
	cd mandelbrot && make clean
	cd pinocchio && make clean
	cd plasma && make clean
	cd pyramide && make clean
	cd rotozoom && make clean
	cd rotozoom_without_UART && make clean
	cd scene_viewer && make clean
	cd shadow_map && make clean
