#USER_SI570 300 MHz
set_property PACKAGE_PIN AL7            [get_ports {user_si570_sysclk_clk_n}] 
set_property IOSTANDARD  DIFF_SSTL12    [get_ports {user_si570_sysclk_clk_n}]
set_property PACKAGE_PIN AL8            [get_ports {user_si570_sysclk_clk_p}]
set_property IOSTANDARD  DIFF_SSTL12    [get_ports {user_si570_sysclk_clk_p}]

#set_property PACKAGE_PIN R9             [get_ports {SFP_REC_CLOCK_C_N}]   
#set_property IOSTANDARD  LVDS           [get_ports {SFP_REC_CLOCK_C_N}]   
#set_property PACKAGE_PIN R10            [get_ports {SFP_REC_CLOCK_C_P}]   
#set_property IOSTANDARD  LVDS           [get_ports {SFP_REC_CLOCK_C_P}]   
#set_property PACKAGE_PIN AG4            [get_ports {HDMI_REC_CLOCK_C_N}]  
#set_property IOSTANDARD  LVDS           [get_ports {HDMI_REC_CLOCK_C_N}]  
#set_property PACKAGE_PIN AG5            [get_ports {HDMI_REC_CLOCK_C_P}]  
#set_property IOSTANDARD  LVDS           [get_ports {HDMI_REC_CLOCK_C_P}]  
#set_property PACKAGE_PIN AG6            [get_ports {HDMI_TX_LVDS_OUT_N}]  
#set_property IOSTANDARD  LVDS           [get_ports {HDMI_TX_LVDS_OUT_N}]  
#set_property PACKAGE_PIN AF6            [get_ports {HDMI_TX_LVDS_OUT_P}]  
#set_property IOSTANDARD  LVDS           [get_ports {HDMI_TX_LVDS_OUT_P}]  

#DDR4 COMPONENT 16-BIT U2
set_property PACKAGE_PIN AM8            [get_ports {C0_DDR4_adr[0]}]       
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[0]}]       
set_property PACKAGE_PIN AM9            [get_ports {C0_DDR4_adr[1]}]       
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[1]}]
set_property PACKAGE_PIN AP8            [get_ports {C0_DDR4_adr[2]}]       
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[2]}]       
set_property PACKAGE_PIN AN8            [get_ports {C0_DDR4_adr[3]}]       
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[3]}]       
set_property PACKAGE_PIN AK10           [get_ports {C0_DDR4_adr[4]}]  
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[4]}]       
set_property PACKAGE_PIN AJ10           [get_ports {C0_DDR4_adr[5]}]       
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[5]}]       
set_property PACKAGE_PIN AP9            [get_ports {C0_DDR4_adr[6]}]       
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[6]}]       
set_property PACKAGE_PIN AN9            [get_ports {C0_DDR4_adr[7]}]       
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[7]}]       
set_property PACKAGE_PIN AP10           [get_ports {C0_DDR4_adr[8]}]       
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[8]}]       
set_property PACKAGE_PIN AP11           [get_ports {C0_DDR4_adr[9]}]       
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[9]}]       
set_property PACKAGE_PIN AM10           [get_ports {C0_DDR4_adr[10]}]      
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[10]}]      
set_property PACKAGE_PIN AL10           [get_ports {C0_DDR4_adr[11]}]      
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[11]}]      
set_property PACKAGE_PIN AM11           [get_ports {C0_DDR4_adr[12]}]      
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[12]}]      
set_property PACKAGE_PIN AL11           [get_ports {C0_DDR4_adr[13]}]      
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[13]}]      
set_property PACKAGE_PIN AJ7            [get_ports {C0_DDR4_adr[14]}] 
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[14]}] 
set_property PACKAGE_PIN AL5            [get_ports {C0_DDR4_adr[15]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[15]}]
set_property PACKAGE_PIN AJ9            [get_ports {C0_DDR4_adr[16]}]
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_adr[16]}]
set_property PACKAGE_PIN AK12           [get_ports {C0_DDR4_ba[0]}]      
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_ba[0]}]      
set_property PACKAGE_PIN AJ12           [get_ports {C0_DDR4_ba[1]}]      
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_ba[1]}]      
set_property PACKAGE_PIN AK4            [get_ports {C0_DDR4_dq[0]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[0]}]      
set_property PACKAGE_PIN AK5            [get_ports {C0_DDR4_dq[1]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[1]}]      
set_property PACKAGE_PIN AN4            [get_ports {C0_DDR4_dq[2]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[2]}]      
set_property PACKAGE_PIN AM4            [get_ports {C0_DDR4_dq[3]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[3]}]      
set_property PACKAGE_PIN AP4            [get_ports {C0_DDR4_dq[4]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[4]}]      
set_property PACKAGE_PIN AP5            [get_ports {C0_DDR4_dq[5]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[5]}]      
set_property PACKAGE_PIN AM5            [get_ports {C0_DDR4_dq[6]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[6]}]      
set_property PACKAGE_PIN AM6            [get_ports {C0_DDR4_dq[7]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[7]}]      
set_property PACKAGE_PIN AK2            [get_ports {C0_DDR4_dq[8]}]
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[8]}]      
set_property PACKAGE_PIN AK3            [get_ports {C0_DDR4_dq[9]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[9]}]      
set_property PACKAGE_PIN AL1            [get_ports {C0_DDR4_dq[10]}]     
set_property IOSTANDARD  POD12_DCI      [get_ports {C0_DDR4_dq[10]}]     
set_property PACKAGE_PIN AK1            [get_ports {C0_DDR4_dq[11]}]     
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[11]}]     
set_property PACKAGE_PIN AN1            [get_ports {C0_DDR4_dq[12]}]     
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[12]}]     
set_property PACKAGE_PIN AM1            [get_ports {C0_DDR4_dq[13]}]     
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[13]}]     
set_property PACKAGE_PIN AP3            [get_ports {C0_DDR4_dq[14]}]     
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[14]}]     
set_property PACKAGE_PIN AN3            [get_ports {C0_DDR4_dq[15]}]     
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dq[15]}]     
set_property PACKAGE_PIN AP6            [get_ports {C0_DDR4_dqs_c[0]}]   
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {C0_DDR4_dqs_c[0]}]  
set_property PACKAGE_PIN AL2            [get_ports {C0_DDR4_dqs_c[1]}]   
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {C0_DDR4_dqs_c[1]}]
set_property PACKAGE_PIN AN6            [get_ports {C0_DDR4_dqs_t[0]}]   
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {C0_DDR4_dqs_t[0]}]       
set_property PACKAGE_PIN AL3            [get_ports {C0_DDR4_dqs_t[1]}]   
set_property IOSTANDARD DIFF_POD12_DCI  [get_ports {C0_DDR4_dqs_t[1]}]   
set_property PACKAGE_PIN AL6            [get_ports {C0_DDR4_dm_n[0]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dm_n[0]}]      
set_property PACKAGE_PIN AN2            [get_ports {C0_DDR4_dm_n[1]}]      
set_property IOSTANDARD POD12_DCI       [get_ports {C0_DDR4_dm_n[1]}]      
set_property PACKAGE_PIN AP7            [get_ports {C0_DDR4_ck_c}]     
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {C0_DDR4_ck_c}]     
set_property PACKAGE_PIN AN7            [get_ports {C0_DDR4_ck_t}]     
set_property IOSTANDARD DIFF_SSTL12_DCI [get_ports {C0_DDR4_ck_t}]     
set_property PACKAGE_PIN AM3            [get_ports {C0_DDR4_cke}]      
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_cke}]      
set_property PACKAGE_PIN AK7            [get_ports {C0_DDR4_bg}]      
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_bg}]      
#set_property PACKAGE_PIN AP1           [get_ports {DDR4_PAR}]      
#set_property IOSTANDARD SSTL12_DCI     [get_ports {DDR4_PAR}]      
set_property PACKAGE_PIN AK8            [get_ports {C0_DDR4_act_n}]    
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_act_n}]    
set_property PACKAGE_PIN AK9            [get_ports {C0_DDR4_odt}]      
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_odt}]      
set_property PACKAGE_PIN AH9            [get_ports {C0_DDR4_reset_n}]
set_property IOSTANDARD  LVCMOS18       [get_ports {C0_DDR4_reset_n}]
set_property PACKAGE_PIN AP2            [get_ports {C0_DDR4_cs_n}]     
set_property IOSTANDARD SSTL12_DCI      [get_ports {C0_DDR4_cs_n}]     

#CPU RESET PUSHBUTTON
set_property PACKAGE_PIN AM13      [get_ports {reset}]   
set_property IOSTANDARD  LVCMOS33  [get_ports {reset}]

#GPIO
#PUSHBUTTON SWITCHES
set_property PACKAGE_PIN AG13      [get_ports {GPIO_PB5_tri_i[0]}] 
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_PB5_tri_i[0]}]
set_property PACKAGE_PIN AF15      [get_ports {GPIO_PB5_tri_i[1]}] 
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_PB5_tri_i[1]}]
set_property PACKAGE_PIN AE15      [get_ports {GPIO_PB5_tri_i[2]}] 
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_PB5_tri_i[2]}]
set_property PACKAGE_PIN AE14      [get_ports {GPIO_PB5_tri_i[3]}] 
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_PB5_tri_i[3]}]  
set_property PACKAGE_PIN AG15      [get_ports {GPIO_PB5_tri_i[4]}] 
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_PB5_tri_i[4]}]  

#DIP SWITCH 8-POLE
set_property PACKAGE_PIN AN14      [get_ports {GPIO_DP8_tri_i[0]}]
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_DP8_tri_i[0]}]
set_property PACKAGE_PIN AP14      [get_ports {GPIO_DP8_tri_i[1]}]
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_DP8_tri_i[1]}]
set_property PACKAGE_PIN AM14      [get_ports {GPIO_DP8_tri_i[2]}]
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_DP8_tri_i[2]}]
set_property PACKAGE_PIN AN13      [get_ports {GPIO_DP8_tri_i[3]}]
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_DP8_tri_i[3]}]
set_property PACKAGE_PIN AN12      [get_ports {GPIO_DP8_tri_i[4]}]
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_DP8_tri_i[4]}]
set_property PACKAGE_PIN AP12      [get_ports {GPIO_DP8_tri_i[5]}]
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_DP8_tri_i[5]}]
set_property PACKAGE_PIN AL13      [get_ports {GPIO_DP8_tri_i[6]}]
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_DP8_tri_i[6]}]
set_property PACKAGE_PIN AK13      [get_ports {GPIO_DP8_tri_i[7]}]
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_DP8_tri_i[7]}]

#LED
set_property PACKAGE_PIN AG14      [get_ports {GPIO_LED8_tri_o[0]}]  
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_LED8_tri_o[0]}]  
set_property PACKAGE_PIN AF13      [get_ports {GPIO_LED8_tri_o[1]}]  
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_LED8_tri_o[1]}]  
set_property PACKAGE_PIN AE13      [get_ports {GPIO_LED8_tri_o[2]}]  
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_LED8_tri_o[2]}]  
set_property PACKAGE_PIN AJ14      [get_ports {GPIO_LED8_tri_o[3]}]  
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_LED8_tri_o[3]}]  
set_property PACKAGE_PIN AJ15      [get_ports {GPIO_LED8_tri_o[4]}]  
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_LED8_tri_o[4]}]  
set_property PACKAGE_PIN AH13      [get_ports {GPIO_LED8_tri_o[5]}]  
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_LED8_tri_o[5]}]  
set_property PACKAGE_PIN AH14      [get_ports {GPIO_LED8_tri_o[6]}]  
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_LED8_tri_o[6]}]  
set_property PACKAGE_PIN AL12      [get_ports {GPIO_LED8_tri_o[7]}]  
set_property IOSTANDARD  LVCMOS33  [get_ports {GPIO_LED8_tri_o[7]}]  

#VGA

####### PMOD0 #######   ####### PMOD1 #######
# 0 -> R0 | 4 -> B0 #   # 0 -> G0 | 4 -> HS #   
# 1 -> R1 | 5 -> B1 #   # 1 -> G1 | 5 -> VS #   
# 2 -> R2 | 6 -> B2 #   # 2 -> G2 | 6 -> -- #   
# 3 -> R3 | 7 -> B3 #   # 3 -> G3 | 7 -> -- #   
#####################   #####################   

# PMOD0_0
set_property PACKAGE_PIN A20 [get_ports {vga_out_r[0]}]        
# PMOD0_1
set_property PACKAGE_PIN B20 [get_ports {vga_out_r[1]}]        
# PMOD0_2
set_property PACKAGE_PIN A22 [get_ports {vga_out_r[2]}]        
# PMOD0_3
set_property PACKAGE_PIN A21 [get_ports {vga_out_r[3]}]        
# PMOD0_4
set_property PACKAGE_PIN B21 [get_ports {vga_out_b[0]}]        
# PMOD0_5
set_property PACKAGE_PIN C21 [get_ports {vga_out_b[1]}]        
# PMOD0_6
set_property PACKAGE_PIN C22 [get_ports {vga_out_b[2]}]        
# PMOD0_7
set_property PACKAGE_PIN D21 [get_ports {vga_out_b[3]}]        
# PMOD1_0
set_property PACKAGE_PIN D20 [get_ports {vga_out_g[0]}]        
# PMOD1_1
set_property PACKAGE_PIN E20 [get_ports {vga_out_g[1]}]        
# PMOD1_2
set_property PACKAGE_PIN D22 [get_ports {vga_out_g[2]}]        
# PMOD1_3
set_property PACKAGE_PIN E22 [get_ports {vga_out_g[3]}]        
# PMOD1_4
set_property PACKAGE_PIN F20 [get_ports vga_out_hs]            
# PMOD1_5
set_property PACKAGE_PIN G20 [get_ports vga_out_vs]     

set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_out_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports vga_out_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_out_vs]

#UART
set_property PACKAGE_PIN E13     [get_ports UART_rxd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_rxd]
set_property PACKAGE_PIN F13     [get_ports UART_txd]
set_property IOSTANDARD LVCMOS33 [get_ports UART_txd]